# Follows is a symbols "review." I don`t remember going over a lot of these in
# previous lessions, though. "Review" may be a misnomer.

puts "********************************************"
puts "Keywords"
puts "********************************************"
puts "`alias` is: a way to override a method but still have the ability to 
puts "use the original functionality of the overridden method. Give it an alias,"
puts "use the alias for the original functionality and override the old name"

puts "`and` is: the logical operator and"
puts "`begin` is: "
puts "`BEGIN` is: "
puts "`break` is: "
puts "`case` is: "
puts "`class` is: "
puts "`def` is: "
puts "`defined?` is: "
puts "`do` is: "
puts "`else` is: "
puts "`elsif` is: "
puts "`end` is: "
puts "`END` is: "
puts "`else` is: "
puts "`ensure` is: "
puts "`false` is: "
puts "`for` is: "
puts "`if` is: "
puts "`in` is: "
puts "`module` is: "
puts "`next` is: "
puts "`nil` is: "
puts "`not` is: "
puts "`or` is: "
puts "`redo` is: "
puts "`rescue` is: "
puts "`retry` is: "
puts "`return` is: "
puts "`self` is: "
puts "`super` is: "
puts "`then` is: "
puts "`true` is: "
puts "`undef` is: "
puts "`unless` is: "
puts "`until` is: "
puts "`when` is: "
puts "`while` is: "
puts "`yield` is: "
puts
puts "********************************************"
puts "Data Types"
puts "********************************************"
puts "`true` is: "
puts "`false` is: "
puts "`nil` is: "
puts "`constants` is: "
puts "`strings` is: "
puts "`numbers` is: "
puts "`ranges` is: "
puts "`arrays` is: "
puts "`hashes` is: "
puts
puts "********************************************"
puts "String Escape Sequences"
puts "********************************************"
puts "`\\` is: "
puts "`\'` is: "
puts "`\"` is: "
puts "`\a` is: "
puts "`\b` is: "
puts "`\f` is: "
puts "`\n` is: "
puts "`\r` is: "
puts "`\t` is: "
puts "`\v` is: "
puts
puts "********************************************"
puts "Operators"
puts "********************************************"
puts "`::` is: "
puts "`[]` is: "
puts "`**` is: "
puts "`-(unary)` is: "
puts "`+(unary)` is: "
puts "`!` is: "
puts "`~` is: "
puts "`*` is: "
puts "`/` is: "
puts "`%` is: "
puts "`+` is: "
puts "`-` is: "
puts "`<<` is: "
puts "`>>` is: "
puts "`&` is: "
puts "`|` is: "
puts "`>` is: "
puts "`>+` is: "
puts "`<` is: "
puts "`<=` is: "
puts "`<=>` is: "
puts "`==` is: "
puts "`===` is: "
puts "`!=` is: "
puts "`=~` is: "
puts "`!~` is: "
puts "`&&` is: "
puts "`||` is: "
puts "`..` is: "
puts "`...` is: "
puts "`` is: "